config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # homepage = root
  resources :home
  root to: redirect("/home")

  # ricerche recenti
  resources :searches, only: [ :create ]

  # ricerca treni (andata, andata/ritorno, pagamento, acquisto confermato)
  get "travels/search", to: "travels#search", as: "travels_search"
  get "travels/return", to: "travels#return", as: "travels_return"
  get "travels/payment", to: "travels#payment", as: "travels_payment"
  post "travels/confirmed_purchase", to: "travels#confirmed_purchase", as: "travels_confirmed_purchase"
  get "travels/confirm", to: "travels#confirm", as: "travels_confirm"


  # registrazione, login, logout
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  # area personale, gestione biglietti
  get "/profile", to: "users#profile", as: "user_profile"
  get "/profile/edit", to: "users#edit", as: "edit_user_profile"
  patch "/profile", to: "users#update"
  delete "profile/destroy/:pnr", to: "tickets#destroy", as: "ticket_destroy"
  get "tickets/edit_time/:pnr/:hpar/:harr", to: "tickets#edit_time", as: "ticket_edit_time"
  patch "tickets/update_time", to: "tickets#update_time", as: "ticket_update_time"

  # dashboard admin
  namespace :admin do
    get "dashboard", to: "dashboard#index"
    resources :users, only: [ :index ]
    resources :tickets, only: [ :index ]
    resources :trains, only: [ :new, :create ]
    resources :travels, param: :cod, except: [ :update ] do
      collection do
        get :search # Per il form
        post :results # Per i risultati
      end
      member do
        get "edit_price/:cod/:part/:dest", to: "travels#edit_price", as: :edit_price
        patch "update_price/:cod/:part/:dest", to: "travels#update_price", as: :update_price
      end
    end
  end


  # stato treno
  get "train_status", to: "train_status#index", as: "train_status"
  get "train_status/show", to: "train_status#show", as: "train_status_show"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  self.table_name = "users"
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :trackable and :timeoutable
  devise :database_authenticatable, :registerable, :recoverable, :validatable,
         :omniauthable, omniauth_providers: [ :google_oauth2 ]

  has_many :searches, foreign_key: "email", primary_key: "email"
  has_many :tickets, foreign_key: "email", primary_key: "email"

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      if auth.info.name
        name_parts = auth.info.name.split(" ", 2) # Dividi il nome in due parti
        user.name = name_parts[0] # Prima parte come nome
        user.surname = name_parts[1] || "" # Seconda parte come cognome (o vuoto se manca)
      end
    end
  end
  def admin?
    self.admin
  end
end

app/controllers/admin/users_controller.rb
module Admin
    class UsersController < ApplicationController
      before_action :authenticate_user!
      before_action :authorize_admin!

      def index
        @users = User.where(admin: false).select(:email, :name, :surname, :provider).order(:surname)
      end
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  def google_oauth2
    user=User.from_omniauth(auth)

    if user.present?
      sign_out_all_scopes
      flash[:success] = t "devise.omniauth_callbacks.success", kind: "Google"
      sign_in_and_redirect user, event: :authentication
    else
      flash[:alert] = t "devise.omniauth_callbacks.failure", kind: "Google", reason: "#{auth.info.email} is not authorized."
      redirect_to new_user_session_path
    end
  end
  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected
  private

  def auth
    @auth ||= request.env["omniauth.auth"]
  end

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  def after_sign_out_path_for(_resource_or_scope)
    new_user_session_path
  end

  def after_sign_in_path_for(_resource_or_scope)
    stored_location_for(_resource_or_scope) || root_path
  end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def profile
    @user = current_user
    @tickets = current_user.tickets
  end

  def edit
    @user = current_user
  end


  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to user_profile_path, notice: "I tuoi dati sono stati aggiornati con successo."
    else
      flash.now[:alert] = "Errore durante l’aggiornamento dei dati."
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :surname, :password, :password_confirmation)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<title>Modifica profilo</title>

<style>
input {
	width: 200px;
}
</style>

<%= form_with model: @user, url: user_profile_path, method: :patch, local: true do |f| %>
  <div class="formhead">Modifica i tuoi dati</div>
  <div class="form-group">
    <%= f.label :name, "Nome" %>
    <%= f.text_field :name, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= f.label :surname, "Cognome" %>
    <%= f.text_field :surname, class: 'form-control', required: true %>
  </div>

<% if false %> 
ERROR undefined method `reset_password_token=' for an instance of User (MANCA ATTRIBUTO NELLA TABELLA)
  <div class="form-group">
    <%= f.label :password, "Nuova Password" %>
    <%= f.password_field :password, class: 'form-control', placeholder: " [invariata]" %>
  </div>

  <div class="">
    <%= f.label :password_confirmation, "Conferma Password" %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>
<% end %>
  <div style="text-align: center;">
    <%= f.submit 'Aggiorna', class: 'button' %>
    <%= link_to 'Annulla', user_profile_path, class: 'button' %>
  </div>
<% end %>

app/views/users/profile.html.erb
<title>Area Personale</title>
<style>
	.form {
		margin: auto;
		margin-top: 50px;
		margin-bottom: 40px;
		text-align: left;
		border-style: solid 0px;
		border-radius: 16px;
		background-color: white;
		min-width: fit-content;
		padding: 16px;
	}
	.info {
		width: 25%;
		min-width: 240px;
		padding-right: 2.5%;
	}
	.dati {
		margin: 0 5% 0 5%;
	}
	.viaggi {
		margin: auto;
		width: auto;
		min-width: auto;
		padding-left: 2.5%;
	}
	.admin {
		text-align: center;
		margin: auto auto 25px auto;
		width: 200px;
	}
	.logout {
		color: white;
		background-color: rgb(180, 0, 0);
		padding: 10px;
		width: fit-content;
	}
	.inline-form {
		display: inline-block;
		margin: 0;
		padding: 0;
	}
</style>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        // Gestisce il toggle dei pulsanti nascosti
        document.querySelectorAll(".toggle-actions").forEach(button => {
            button.addEventListener("click", function() {
                const ticketId = this.dataset.ticketId;
                const actionsDiv = document.getElementById(`actions-${ticketId}`);
                const isActionsVisible = actionsDiv.style.display === "block";

                // Alterna la visibilità dei tasti e cambia il testo del pulsante
                actionsDiv.style.display = isActionsVisible ? "none" : "block";
                this.textContent = isActionsVisible ? "Gestisci" : "Indietro";
            });
        });

        // Gestisce la conferma personalizzata per il tasto "Cancella"
        document.querySelectorAll(".btn-danger").forEach(button => {
            button.addEventListener("click", function(event) {
                event.preventDefault(); // Evita l'azione predefinita
                const confirmDelete = confirm("Sei sicuro di voler eliminare questo biglietto?");
                if (confirmDelete) {
                    this.closest("form").submit(); // Procede con l'eliminazione
                }
            });
        });
    });
</script>

<table class="dati">
	<tr>
		<td class="info">
			<%= form_with url: destroy_user_session_path, method: :delete do %>
			<div class="formhead">I tuoi dati</div>
			<div <% if @user.admin? %> style="text-align: center;" <% end %>>
				<p>Nome: <%= @user.name %></p>
				<p>Cognome: <%= @user.surname %></p>
				<p>Email: <%= @user.email %></p>
				<p>Password: *****</p>
			</div>
			<p style="text-align: center; margin-top: 30px;">
			<%= link_to "Modifica dati", edit_user_profile_path, class: "button" %>
			</p>
			<% end %>
		</td>

		<% if !@user.admin? %>
			<td class="viaggi">
				<div class="form">
					<div class="formhead" style="padding-top: 10px;">I tuoi viaggi</div>
						<% if @tickets == [] %>
							<h4 style="text-align: center; margin-top: 10px;">Non hai ancora acquistato alcun biglietto</h4></td>
						<% else %>
							<div class="container mt-4">
								<table class="table table-striped table-bordered align-middle">
									<% @tickets = @tickets.order(:date, :hpar, :harr) %>
									<% @tickets.each do |ticket| %>
										<tr>
											<td><%= ticket.pnr %></td>
											<td><%= ticket.date.strftime('%d/%m/%Y') %></td>
											<td><%= ticket.part %> &rarr; <%= ticket.dest %></td>
											<td><%= ticket.hpar.strftime('%H:%M') %> &rarr; <%= ticket.harr.strftime('%H:%M') %></td>
											<td><%= ticket.pass %>&#128100;</td>
											<td>€ <%= ticket.price %></td>
											<td style="text-align: center;">
												<button type="button" class="btn btn-primary btn-sm toggle-actions" id="toggleButton" onclick="toggleActions(this)" data-ticket-id="<%= ticket.pnr %>">
													Gestisci
												</button>
												<div class="ticket-actions" id="actions-<%= ticket.pnr %>" style="display: none;">
													<div>
														<% if ticket.date == Date.current %>
															<%= link_to 'Stato Treno', train_status_show_path(code: ticket.cod), 
																class: "btn btn-info btn-sm", style: "margin-top: 5px;" %>
														<% else %>
															<%= button_tag 'Stato Treno', class: "btn btn-info btn-sm", style: "margin-top: 5px;", disabled: true %>
														<% end %>
													</div>
													<div>
														<% if ticket.date > Date.current %>
															<%= link_to "Modifica Orario", ticket_edit_time_path(pnr: ticket.pnr, hpar: ticket.hpar, harr: ticket.harr), method: :get, 
															class: "btn btn-warning btn-sm", style: "margin-top: 5px;" %>
														<% else %>
															<%= button_tag "Modifica Orario", class: "btn btn-warning btn-sm", style: "margin-top: 5px;", disabled: true %> 
														<% end %>
													</div>
													<div>
														<form action="<%= ticket_destroy_path(ticket.pnr) %>" method="post" class="inline-form">
															<input type="hidden" name="_method" value="delete">
															<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
															<% if ticket.date > Date.current %>
																<%= submit_tag "Cancella", class: "btn", style: "color: white; background-color: rgb(180, 0, 0); width: fit-content; padding: 5px;",
																	onclick: "return confirm('Sei sicuro di voler eliminare questo biglietto? Puoi cambiare orario fino al giorno prima della partenza!');"
																%>
															<% else %>
																<%= submit_tag "Cancella", class: "btn", style: "color: white; background-color: rgb(180, 0, 0); width: fit-content; padding: 5px;",
																	onclick: "return confirm('Sei sicuro di voler eliminare questo biglietto?');"
																%>
															<% end %>
														</form>
													</div>
												</div>
											</td>
										</tr>
									<% end %>
								</table>
							</div>
						</div>
					<% end %>
				</div>
			</td>
		<% end %>
	</tr>
</table>
<% if @user.admin? %>
	<%= link_to "AREA FUNZIONALITÁ AMMINISTRATORE", admin_dashboard_path, class: "button admin" %>
<% end %>

	<%= form_with url: destroy_user_session_path, method: :delete do %>
		<%= submit_tag "Logout", class: "logout" %>
	<% end %>