config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # homepage = root
  resources :home
  root to: redirect("/home")

  # ricerche recenti
  resources :searches, only: [ :create ]

  # ricerca treni (andata, andata/ritorno, pagamento, acquisto confermato)
  get "travels/search", to: "travels#search", as: "travels_search"
  get "travels/return", to: "travels#return", as: "travels_return"
  get "travels/payment", to: "travels#payment", as: "travels_payment"
  post "travels/confirmed_purchase", to: "travels#confirmed_purchase", as: "travels_confirmed_purchase"
  get "travels/confirm", to: "travels#confirm", as: "travels_confirm"


  # registrazione, login, logout
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  # area personale, gestione biglietti
  get "/profile", to: "users#profile", as: "user_profile"
  get "/profile/edit", to: "users#edit", as: "edit_user_profile"
  patch "/profile", to: "users#update"
  delete "profile/destroy/:pnr", to: "tickets#destroy", as: "ticket_destroy"
  get "tickets/edit_time/:pnr/:hpar/:harr", to: "tickets#edit_time", as: "ticket_edit_time"
  patch "tickets/update_time", to: "tickets#update_time", as: "ticket_update_time"

  # dashboard admin
  namespace :admin do
    get "dashboard", to: "dashboard#index"
    resources :users, only: [ :index ]
    resources :tickets, only: [ :index ]
    resources :trains, only: [ :new, :create ]
    resources :travels, param: :cod, except: [ :update ] do
      collection do
        get :search # Per il form
        post :results # Per i risultati
      end
      member do
        get "edit_price/:cod/:part/:dest", to: "travels#edit_price", as: :edit_price
        patch "update_price/:cod/:part/:dest", to: "travels#update_price", as: :update_price
      end
    end
  end


  # stato treno
  get "train_status", to: "train_status#index", as: "train_status"
  get "train_status/show", to: "train_status#show", as: "train_status_show"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Outfit:wght@100..900&display=swap">
<link rel="icon" href="<%= asset_path('LogoEasyRail.jpg') %>" type="image/jpeg">
<link rel="apple-touch-icon" href="<%= asset_path('LogoEasyRail.jpg') %>" type="image/jpeg">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" defer></script>

  	<head>
		<!--Barra superiore-->
    	<header class="topnav">
			<nav>
				<%= link_to "EasyRail", root_path, class: "titolo" %>
				<div class="log dropdown">
					<% if user_signed_in? %>
						<button class="dropbtn"><%= current_user.name %></button>
						<div class="dropdown-content">
							<%= link_to "Area personale", user_profile_path , class: "center" %>
							<%= form_with url: destroy_user_session_path, method: :delete do %>
								<%= submit_tag "Logout", class: "logged" %>
							<% end %>
						</div>

					<% else %>
						<button class="dropbtn">Accedi</button>
						<div class="dropdown-content">
							<%= link_to "Login", new_user_session_path, class: "center" %>
							<%= link_to "Registrati", new_user_registration_path, class: "center" %>
						</div>
					<% end %>
        		</div>
				<%= link_to "Home", root_path, class: (current_page?("/home") ? "active center" : "center") %>
				<%= link_to "Stato treno", train_status_path, class: (current_page?(train_status_path) || current_page?("/train_status/show") ? "active center" : "center") %>
			</nav>
		</header>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body data-user-logged-in="<%= user_signed_in? %>">
    <%= yield %>
  </body>
  
	<% unless footer_hidden? %>
	<!--Parte inferiore-->
		<footer>
			<table style="width: 100%;">
				<tr>
					<td style="text-align: left;">
						<p>EasyRail &copy;</p>
						<p>Un progetto per Lab. ASSI (Laboratorio di Architetture Software e Sicurezza Informatica) - A.A. 2024/25</p>
						<p>Proff. Leonardo Querzoni e Daniele Cono D'Elia</p>
					</td>
				<tr>	
					<td>Capitale Sociale 0&euro;.<p>Tutti i diritti riservati.</p></td>
					<td style="text-align: right;">Sede legale Università La Sapienza -	Edificio Marco Polo, Viale Scalo San Lorenzo, 82, Roma</td>
				</tr>
			</table>
		</footer>
	<% end %>
</html>